  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      


configuracao:
  monolito:
    url: http://localhost:8080
server:
  port: 8085
spring:
  application:
    name: 'pagamento'

  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:pagamento
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
